---
:skip: true
:truncate: true
:model_class: Occto::FitPlanByPowerGeneratorGroup
:sources:
- :fields:
    id: 
    fit_plan_id: 
    power_generator_group_id: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: 
  :where: 
