---
:skip: true
:truncate: true
:model_class: Occto::PlanByCompany
:fields:
  id: 
  plan_id: 
  company_id: 
  created_by: 
  updated_by: 
  created_at: 
  updated_at: 
:from: base_table_name
:where: 0 = 0
