=== 翌日調達計画詳細

==== 概要

[.lead]
任意のBG/日付における翌日調達計画のサマリを表示するとともに、PLSの実行及び計画提出業務を行う

===== 画面イメージ

[plantuml]
--
salt
{+
  { パワオプ東京BG | 2019/02/01 }
  { ステータス: | 未提出 }
  {* 計画作成 | アップロード | ダウンロード | 一括提出
   一括提出 | 広域提出 | JBU提出 | JEPX発注 }
  {#
  コマ | 需要 | SPOT | 1時間 | JBU | FIT | 相対 | 供給合計 | 速報値 | IMB
  00:00| 1000 | 500  | 0     | 200 | 100 | 200  | 1000     |  990   | -10
  00:30| 1000 | 500  | 0     | 200 | 100 | 200  | 1000     |  990   | -10
  01:00| 1000 | 500  | 0     | 200 | 100 | 200  | 1000     |  990   | -10
  01:30| 1000 | 500  | 0     | 200 | 100 | 200  | 1000     |  990   | -10
  (48コマ分作成する) | *
  }
}
--

===== I/O関連図

[plantuml]
--
rectangle {
  database "需要予測データ(PPS)" as input_a
  database "電力使用量(速報値)" as input_b
  database "広域需要調達計画(翌日)" as io_a
  database "広域需要調達計画(翌日)BGメンバー別データ" as io_b
  database "広域需要調達計画(翌日)詳細値データ" as io_c

  ("翌日調達計画詳細") as (prog)
}

input_a --> prog : input
input_b --> prog : input
prog <--> io_a : input/output
prog <--> io_b : input/output
prog <--> io_c : input/output
--

===== I/O

|======================================
| 名称 | 物理名 | 種類 | I/O種別 | 備考
| 需要予測データ(PPS) |        |      |         |
| 広域需要調達計画(翌日) |        |      |         |
| 広域需要調達計画(翌日)BGメンバー別データ|        |      |         |
| 広域需要調達計画(翌日)詳細値データ |        |      |         |
|======================================

<<<

==== 画面項目定義

==== 詳細情報
|======================================
| 項目名 | 物理項目名 | 取得元 | I/O | 備考
|======================================

<<<

==== 機能詳細

===== 初期表示

* 遷移元の画面より、BG、処理日をパラメータとして取得
* 広域需要調達計画(翌日)の状況に応じてステータスを表示する
* 広域需要調達計画及び子テーブルより指定されたBG/日付の翌日調達計画データを取得し、表に表示する
* 速報値がある場合はBG別に集計した速報値を表示しインバランスを計算する

===== 計画作成ボタン押下時

* 登録された需要予測データをもとにPLSを実行し、需要調達計画を作成する(詳細はバッチ仕様書参照)
* データが作成された後、作成された計画を表示する

===== ダウンロードボタン押下時

* 需要調達計画を広域提出用xml形式でダウンロードする

===== アップロードボタン押下時

* ファイル選択ダイアログを開く
* 広域提出用xml形式を選択してアップロードボタンを押下すると、当該xmlより広域需要調達計画(翌日)の登録/更新を行う
** この際、BG及び提出日が違う場合はエラーとする

===== 一括提出ボタン押下時

JBU提出、JEPX発注、広域提出を一括して実施する
(PLS未実施時にはボタンを無効とする)

===== JBU提出押下時

作成された計画に基づきJBUへの発注メールを送信する
(PLS未実施時にはボタンを無効とする)

===== JEPX発注押下時

作成された計画に基づきJEPXへの発注を行う
(JEPXがクローズしている時間帯には処理不可とする)
(PLS未実施時にはボタンを無効とする)

===== 広域提出押下時

作成された計画に基づき広域機関への提出を行う
(JEPXがクローズしている時間帯には処理不可とする)
(PLS未実施時にはボタンを無効とする)

広域、JEPX、託送への送信状況を把握できるようなステータス管理
ポジション登録の修正機能について検討する

<<<

