=== 翌日需要調達計画状況一覧

==== 概要

[.lead]
BG別に翌日需要調達計画及び関連する業務の進捗状況を確認する
各業務画面へのハブとなる

===== 画面イメージ

[plantuml]
--
salt
{
  { ^パワオプ東京BG^ }
  { "<<前週" |  ^2019/02/01^ | "翌週>>" }
  {#
    .   | BG                         | PPS1                           | PPS2                          | PPS3..
    2/1 |{#計画確認|実績確認}        |{#FIT確認|需要予測結果}         |{#FIT確認|需要予測結果}        |{#FIT確認|需要予測結果}
    2/2 |{#計画(提出済み)|#一時間前} |{#FIT(提出済)|需要予測(登録済)} |{#FIT(作成済)|需要予測(未登録)}|{#FIT(未取込)|需要予測(未登録)}
    2/3 |{#計画(提出済み)}           |{#FIT(未登録)|需要予測(未登録)} |{#FIT(未登録)|需要予測(未登録)}|{#FIT(未登録)|需要予測(未登録)}
    2/4 |{#計画(作成済)}             |{#FIT(未登録)|需要予測(未登録)} |{#FIT(未登録)|需要予測(未登録)}|{#FIT(未登録)|需要予測(未登録)}
    2/5 |{#計画(未作成)}             |{#FIT(未登録)|需要予測(未登録)} |{#FIT(未登録)|需要予測(未登録)}|{#FIT(未登録)|需要予測(未登録)}
    2/6 | .                          | .                              | .
    2/7 | .                          | .                              | .
  }
}
--

===== I/O関連図

[plantuml]
--
rectangle {
  database "PPS別需要予測データ" as input_a
  database "発電BG予測データ" as input_b
  database "翌日調達計画データ" as input_c

  (翌日需要調達計画状況一覧) as (prog)
}

input_a --> prog : input
input_b --> prog : input
input_c --> prog : input
--

===== I/O

|======================================
| 名称                 | 物理名 | 種類 | I/O種別 | 備考
| PPS別需要予測データ  |        | DB   | I       |
| 発電BG予測データ     |        | DB   | I       |
| 翌日調達計画データ   |        | DB   | I       |
|======================================

<<<

==== 画面項目定義

==== 詳細情報
|======================================
| 項目名 | 物理項目名 | 取得元 | I/O | 備考
|======================================

<<<

==== 機能詳細

===== 初期表示

ユーザーがBG管理者の場合は、そのBGを検索対象BGとする、そうでない場合はBGのドロップダウンリストの最初を検索対象BGとする

システム日時を取得し、その日付の1日前を開始日とする
開始日から1週間後を終了日とする

I/O定義に列挙されたDBについて、検索対象BGもしくはBGメンバーのデータを開始日から終了日まで取得し、定義に従ってステータスを表示する

===== BG変更時

BGが変更された場合は、検索対象BGを変更して、表を再表示する

===== 前週ボタン押下時

開始日及び終了日を1週間前に変更し、表を再表示する

===== 次週ボタン押下時

開始日及び終了日を1週間後に変更し、表を再表示する

===== BG欄の計画リンク押下時

翌日調達計画詳細画面に遷移する

===== BG欄の一時間前リンク押下時

一時間前市場調達詳細画面に遷移する

===== PPS欄のFITリンク押下時

発電BG予測詳細画面に遷移する

===== PPS欄の需要リンク押下時

需要予測詳細(PPS単位)に遷移する

<<<

