---
:truncate: true
:model_class: Pl::BaseDatumFixed
:sources:
- :fields:
    id: 
    facility_group_id: 
    type: 
    date: 
    time_index_id: 
    amount_actual: 
    amount_planned: 
    amount_loss: 
    amount_imbalance: 
    power_factor_rate: 
    sales_basic_charge: 
    sales_mater_rate_charge: 
    sales_fuel_cost_adjustment: 
    sales_cost_adjustment: 
    sales_special_discount: 
    usage_jbu: 
    usage_jepx_spot: 
    usage_jepx_1hour: 
    usage_fit: 
    usage_matching: 
    supply_jbu_basic_charge: 
    supply_jbu_fuel_cost_adjustment: 
    supply_jepx_spot: 
    supply_jepx_1hour: 
    supply_fit: 
    supply_imbalance: 
    supply_wheeler_fundamental_charge: 
    supply_wheeler_mater_rate_charge: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: 
  :where: 
