---
:table_name: explanatory_variables
:table_type: :simple
:fields:
- id
- district_id
- customer_id
- corporation_name
- is_holiday
- is_national_holiday
- temperature
- weather
- weather_code
- weekday
- discomfort_index
- time
- value
- real_value
- two_day_pre_time
- two_day_pre_value
- one_week_pre_time
- one_week_pre_value
- two_week_pre_time
- two_week_pre_value
- two_day_pre_avg
- four_coma_pre_avg
- pre_day_time
- pre_day_value
- pre_day_avg
- humidity
- observe_id
- division_id
- contract_id
- pps_id
- facility_pref
- supply_method_id
- base_power
- tbl_voltage_id
- customer_count
- active
- created_at
