---
:table_name: tbl_role_item_range
:table_type: :key_value
:fields:
- tbl_role_id
- customer_display_range
- customer_registration_range
- customer_delete_range
- customer_export_range
- user_display_range
- user_registration_range
- user_delete_range
- role_display_range
- role_registration_range
- role_delete_range
- company_display_range
- company_registration_range
- company_delete_range
- contract_display_range
- contract_registration_range
- contract_delete_range
- demandforecast_display_range
- demandforecast_registration_range
- demandforecast_delete_range
- district_display_range
- district_registration_range
- district_delete_range
- division_display_range
- division_registration_range
- division_delete_range
- importcsv_display_range
- importcsv_registration_range
- importcsv_delete_range
- schedule_display_range
- schedule_registration_range
- schedule_delete_range
- supplyanddemand_display_range
- supplyanddemand_registration_range
- supplyanddemand_delete_range
- voltage_display_range
- voltage_registration_range
- voltage_delete_range
- worksupport_display_range
- worksupport_registration_range
- worksupport_delete_range
- workflow_display_range
- workflow_registration_range
- workflow_delete_range
- claim_display_range
- claim_registration_range
- claim_delete_range
- claim_report_range
- claim_export_range
- contractcustomer_display_range
- contractcustomer_registration_range
- contractcustomer_delete_range
- facility_display_range
- facility_registration_range
- facility_delete_range
- contractitemgroup_display_range
- contractitemgroup_registration_range
- contractitemgroup_delete_range
- contractitem_display_range
- contractitem_registration_range
- contractitem_delete_range
- jbu_display_range
- jbu_registration_range
- jbu_delete_range
- pls_display_range
- pls_registration_range
- pls_delete_range
- lowvoltagemaster_display_range
- lowvoltagemaster_registration_range
- lowvoltagemaster_delete_range
- powersupply_display_range
- powersupply_registration_range
- powersupply_delete_range
- bg_display_range
- bg_registration_range
- bg_delete_range
- costadjustment_display_range
- costadjustment_registration_range
- costadjustment_delete_range
- claimhigh_display_range
- claimhigh_registration_range
- claimhigh_delete_range
- claimhigh_approval_range
- claimhigh_export_range
- claimhigh_report_range
- claimlow_display_range
- claimlow_registration_range
- claimlow_delete_range
- claimlow_approval_range
- claimlow_export_range
- claimlow_report_range
- meterratesetting_display_range
- meterratesetting_registration_range
- meterratesetting_delete_range
- agency_display_range
- agency_registration_range
- agency_delete_range
- agencyreward_display_range
- agencyreward_registration_range
- agencyreward_delete_range
- settlementagent_display_range
- mst_payment_display_range
- mst_payment_registration_range
- mst_payment_delete_range
- mst_template_display_range
- mst_template_registration_range
- mst_template_delete_range
- apply_export_range
- coop_cis_display_range
- mst_powprice_display_range
- mst_powprice_registration_range
- mst_powprice_delete_range
- mst_powprice_export_range
