---
:table_name: tbl_role_item
:table_type: :key_value
:fields:
- tbl_role_id
- customer_display
- customer_registration
- customer_delete
- customer_export
- user_display
- user_registration
- user_delete
- role_display
- role_registration
- role_delete
- company_display
- company_registration
- company_delete
- apply_display
- apply_registration
- apply_delete
- workflow_display
- workflow_registration
- workflow_delete
- worksupport_display
- worksupport_registration
- worksupport_delete
- contract_display
- contract_registration
- contract_delete
- demandforecast_display
- demandforecast_registration
- demandforecast_delete
- district_display
- district_registration
- district_delete
- importcsv_display
- importcsv_registration
- importcsv_delete
- schedule_display
- schedule_registration
- schedule_delete
- supplyanddemand_display
- supplyanddemand_registration
- supplyanddemand_delete
- voltage_display
- voltage_registration
- voltage_delete
- division_display
- division_registration
- division_delete
- balancingmonitoring_display
- balancingmonitoring_registration
- balancingmonitoring_delete
- plan_display
- plan_registration
- plan_delete
- claim_display
- claim_registration
- claim_delete
- claim_report
- claim_export
- claim_approval
- plcalculation_display
- contractcustomer_display
- contractcustomer_registration
- contractcustomer_delete
- facility_display
- facility_registration
- facility_delete
- contractitemgroup_display
- contractitemgroup_registration
- contractitemgroup_delete
- contractitem_display
- contractitem_registration
- contractitem_delete
- jbu_display
- jbu_registration
- jbu_delete
- pls_display
- pls_registration
- pls_delete
- lowvoltagemaster_display
- lowvoltagemaster_registration
- lowvoltagemaster_delete
- powersupply_display
- powersupply_registration
- powersupply_delete
- bg_display
- bg_registration
- bg_delete
- costadjustment_display
- costadjustment_registration
- costadjustment_delete
- claimhigh_display
- claimhigh_registration
- claimhigh_delete
- claimhigh_approval
- claimhigh_export
- claimhigh_report
- claimlow_display
- claimlow_registration
- claimlow_delete
- claimlow_approval
- claimlow_export
- claimlow_report
- meterratesetting_display
- meterratesetting_registration
- meterratesetting_delete
- agency_display
- agency_registration
- agency_delete
- agencyreward_display
- agencyreward_registration
- agencyreward_delete
- settlementagent_display
- positionmanagement_display
- batchsituation_display
- time_period_delete
- time_period_registration
- time_period_display
- date_delete
- date_registration
- date_display
- day_of_week_delete
- day_of_week_registration
- day_of_week_display
- monthly_delete
- monthly_registration
- monthly_display
- mst_payment_display
- mst_payment_registration
- mst_payment_delete
- mst_template_display
- mst_template_registration
- mst_template_delete
- apply_export
- coop_cis_display
- mst_powprice_display
- mst_powprice_registration
- mst_powprice_delete
- mst_powprice_export
