---
:table_name: tbl_facility
:table_type: :key_value
:fields:
- facility_name
- supplying_point_number
- tbl_contract_customer_id
- facility_number
- payment_method_id
- shipping_method_id
- tbl_district_id
- claim_destination_flg
- tbl_division_id
- tbl_contract_id
- tbl_voltage_id
- supply_voltage
- contract_power_calc_method_id
- consultation_power
- contractcustomer_name
- supply_method_id
- district_name
- base_power
- division_name
- tbl_observe_id
- area_name
- prediction_type_id
- switching_flg
- facility_characteristic
- holiday_setting
- vacation_memo
- supply_start_date
- supply_end_date
- facility_tel
- facility_fax
- facility_email
- facility_url
- facility_zip
- facility_pref
- tbl_agency_id
- facility_city
- agency_name
- facility_address
- facility_person_in_charge
- facility_person_in_charge_kana
- created
- company_name
- created_user_id
- modified
- modified_user_id
- pps_id
- claim_closing_date
- peak_shift_discount
- spare_power_transmission
- latitude
- longitude
- foreign_code_1
- foreign_code_2
- foreign_code_3
- fuel_cost_calc_month_flg
- auto_prediction
- manual_priority_from
- manual_priority_to
