---
:table_name: tbl_customer
:table_type: :key_value
:fields:
- zip
- pref
- city
- address
- tel
- fax
- created
- created_user_id
- modified
- modified_user_id
- customer_code
- billing_code
- customer_number
- division_id
- corporation_name
- facilities_name
- voltage_id
- district_id
- contract_id
- email
- url
- charge
- charge_kana
- contract_power
- supply_voltage
- payment_method_id
- latitude
- longitude
- observe_id
- memo
- division_name
- voltage_name
- district_name
- contract_name
- pps_id
- pps_name
- supplying_point_number
- base_power
- destination_zip
- destination_address
- destination_name
- supply_start_date
- supply_end_date
- tbl_user_id
- contract_power_calc_method_id
- shipping_method_id
- parent_id
- us_user_name
- supply_method_id
- parent_name
- area_name
- prediction_type_id
- facilities_number
- switching
- customer_characteristics
- holiday_setting
- long_vacation
