---
:table_name: tbl_claim
:table_type: :key_value
:fields:
- claim_status
- claim_classification
- claim_type
- tbl_user_id
- us_user_name
- sche_claim_payment_date
- claim_ym
- intranote
- bank1_id
- bank2_id
- bank3_id
- claim_no
- tbl_customer_id
- subject
- total_amount
- total_amount_tax
- taxtype
- taxrate
- fraction
- fraction_tax
- ba_bankacc_name
- ba1_bank_no
- ba1_ba_type
- ba1_bank_name
- ba1_branch_name
- ba2_bank_no
- ba2_ba_type
- ba2_bank_name
- ba2_branch_name
- ba3_bank_no
- ba3_ba_type
- ba3_bank_name
- ba3_branch_name
- note
- created
- created_user_id
- modified
- modified_user_id
- conventional_total_amount
- conventional_total_amount_tax
- billing_code
- place_specify_number
- destination_name
- destination_address
- corporation_name
- destination_zip
- claim_source
