---
:table_name: tbl_prediction_history
:table_type: :simple
:fields:
- id
- customer_id
- dummy_customer_id
- pps_id
- district_id
- time
- before_power_loss
- after_power_loss
- created
- created_user_id
- modified
- modified_user_id
