---
:table_name: tbl_peak_forecast_alert
:table_type: :simple
:fields:
- tbl_customer_id
- pps_id
- tbl_district_id
- alart_delivery_kbn
- threshold
- alert_target_start_time
- alert_target_end_time
- alert_target_days_sunday
- alert_target_days_monday
- alert_target_days_tuesday
- alert_target_days_wednesday
- alert_target_days_thursday
- alert_target_days_friday
- alert_target_days_saturday
- power_threshold_1
- power_threshold_2
- power_threshold_3
- power_threshold_4
- power_threshold_5
- power_threshold_6
- power_threshold_7
- power_threshold_8
- power_threshold_9
- power_threshold_10
- power_threshold_11
- power_threshold_12
- power_threshold_13
- power_threshold_14
- power_threshold_15
- power_threshold_16
- power_threshold_17
- power_threshold_18
- power_threshold_19
- power_threshold_20
- power_threshold_21
- power_threshold_22
- power_threshold_23
- power_threshold_24
- power_threshold_25
- power_threshold_26
- power_threshold_27
- power_threshold_28
- power_threshold_29
- power_threshold_30
- power_threshold_31
- power_threshold_32
- power_threshold_33
- power_threshold_34
- power_threshold_35
- power_threshold_36
- power_threshold_37
- power_threshold_38
- power_threshold_39
- power_threshold_40
- power_threshold_41
- power_threshold_42
- power_threshold_43
- power_threshold_44
- power_threshold_45
- power_threshold_46
- power_threshold_47
- power_threshold_48
- email
- created
- created_user_id
- modified
- modified_user_id
