---
:table_name: tbl_apply
:table_type: :key_value
:fields:
- place_specify_number
- apply_contract_number
- apply_customer_name
- apply_customer_kana
- apply_address1
- apply_address2
- apply_tel
- apply_email
- switch_date
- created
- created_user_id
- modified
- modified_user_id
- switch_apply_status
- switch_apply_number
- disuse_result_code
- disuse_result_text
- disuse_message_code
- disuse_message_text
- inquiry_result_code
- inquiry_result_text
- inquiry_message_code
- inquiry_message_text
- application_result_code
- application_result_text
- application_message_code
- application_message_text
- stop_transacton_number
- apply_transaction_number
- disuse_modified
- inquiry_modified
- application_modified
- credit_member_id
- apply_district_id
- apply_supply_voltage
- apply_usage_id
- apply_zip
- apply_pref
- apply_city
- apply_company_name
- apply_relation_id
- apply_contract_address_flg
- apply_contract_zip
- apply_contract_pref
- apply_contract_city
- apply_contract_address
- apply_contract_address2
- campaign_code
- apply_supply_capacity
- campaign_company
- moving_kbn
- moving_scheduled_date
- use_credit_card
- apply_memo
- apply_view_password
- apply_agentcode
- apply_registryurl
- apply_district_name
- apply_front_memo
- apply_supply_start_date
- shipping_method_id
- delete_flg
- apply_ryokin_cd
- supply_start_flg
