---
:table_name: tbl_company
:table_type: :key_value
:fields:
- company_name
- company_kana
- zip
- pref
- city
- address
- tel
- fax
- email
- logo_image_id
- seal_image_id
- allocate
- taxtype
- taxrate
- fraction
- fraction_tax
- bankacc_name
- approval_estimate
- approval_received
- approval_order
- approval_claim
- approval_sendmail_flg
- created
- created_user_id
- modified
- modified_user_id
- tbl_user_id
- us_user_name
- tel1
- tel2
- tel3
- account_key
- fax1
- fax2
- fax3
- ene_company_code
- certificate_file_id
- payment_site_id
- payment_site_pass
- certificate_key_file
- alart_delivery_kbn
- payment_site_flg
- occto_userid
- occto_password
- occto_certificate_filename
- jepx_userid
- jepx_password
- jepx_certificate_filename
- claimlow_create_flg
