---
:table_name: tbl_claim_high_item
:table_type: :key_value
:fields:
- tbl_claim_id
- district_name
- contract_name
- itemorder
- code
- caption
- count
- unit
- price
- rowprice
- note
- conventional_flg
- created
- created_user_id
- modified
- modified_user_id
