---
:table_name: tbl_plcalculation_data2
:table_type: :simple
:fields:
- id
- acc_id
- customer_id
- district_id
- time
- fixed_power
- jbu
- jepx_500
- jepx_100
- jbu_position
- jbu_rate
- jbu_price
- jbu_price_r
- area_price
- jepx_500_price
- jepx_500_price_r
- jepx_100_price
- jepx_100_price_r
- interchange
- interchange_price
- interchange_price_r
- etc1
- etc1_price
- etc2
- etc2_price
- etc3
- etc3_price
- etc4
- etc4_price
- jbu_merter_price
- jbu_fuel_cost_adjustment_price
- inbalance_price
- consignment_charge_price
- consignment_meterrate_charge_price
- pps_renewable_energy_cost_price
- supplier_total
- supplier_total_r
- supplier_unit
- supplier_unit_r
- ratio
- ratio_r
- sales_per_kwh
- sales_per_kwh_r
- meter_rate_price
- fuel_cost_adjustment
- sales_per_unit
- sales_per_unit_r
- total_amount
- total_amount_r
- gross
- gross_r
- profit_rate
- profit_rate_r
- created
