---
:table_name: tbl_plcalculation_data_pps
:table_type: :simple
:fields:
- id
- acc_id
- district_id
- time
- total_coma_sum
- total
- jbu
- jepx_500
- jepx_100
- interchange
- etc1
- etc2
- etc3
- etc4
- total_monthly_sum
- jbu_monthly_sum
- jepx_500_monthly_sum
- jepx_100_monthly_sum
- interchange_monthly_sum
- etc1_monthly_sum
- etc2_monthly_sum
- etc3_monthly_sum
- etc4_monthly_sum
- jbu_rate
- jbu_rate_r
- jbu_price
- jbu_price_sum
- jbu_meter_rate
- jbu_meterrate_price
- jbu_meterrate_price_sum
- area_price
- jepx_500_price
- jepx_500_price_sum
- jepx_100_price
- jepx_100_price_r
- interchange_price
- interchange_price_r
- etc1_price
- etc2_price
- etc3_price
- etc4_price
- a1
- a2
- stock_shortage
- shortage_price
- stock_surplus
- surplus_price
- stock_shortage_sum
- shortage_price_sum
- stock_surplus_sum
- surplus_price_sum
- inbalance_sum
- consignment_basic_rate
- consignment_charge
- consignment_charge_price
- consignment_charge_price_sum
- consignment_meterrate_charge
- consignment_meterrate_charge_price
- consignment_meterrate_charge_price_sum
- renewable_energy_cost_price
- renewable_energy_cost_price_sum
- fuel_cost_adjustment_price
- fuel_cost_adjustment_price_sum
- supplier_total
- supplier_total_sum
- area_actual_power
- area_actual_power_sum
- area_fixed_power
- area_fixed_power_sum
- sales_per_unit
- total_amount
- gross
- profit_rate
- created
