---
:table_name: tbl_pls
:table_type: :key_value
:fields:
- tbl_bg_id
- bg_name
- unit_purchased_jepx_spot
- unit_purchased_jepx_intraday
- unit_purchased_jbu
- unit_purchased_other1
- unit_purchased_other2
- unit_purchased_other3
- unit_purchased_inbalance_shortage
- unit_purchased_inbalance_surplus
- unit_max_jepx_spot
- unit_max_jepx_intraday
- unit_max_jbu
- unit_max_other1
- unit_max_other2
- unit_max_other3
- unit_max_inbalance_shortage
- unit_max_inbalance_surplus
- unit_min_jepx_spot
- unit_min_jepx_intraday
- unit_min_jbu
- unit_min_other1
- unit_min_other2
- unit_min_other3
- unit_min_inbalance_shortage
- unit_min_inbalance_surplus
- loss_rate
- beta_value
- before_hours_trading_rate
- meter_rate_summer_season_daytime
- meter_rate_other_season_daytime
- meter_rate_night
- meter_rate_peak_time
- created
- created_user_id
- modified
- modified_user_id
