---
:table_name: tbl_claim_high
:table_type: :key_value
:fields:
- created
- created_user_id
- modified
- modified_user_id
- company_address1
- claim_ym
- company_address2
- company_name
- company_tel
- claim_destination_zip
- claim_destination_address
- claim_destination_name
- claim_subject
- facility_name
- supplying_point_number
- supplying_point_address
- period
- payment_method_id
- bank_name
- bankacc_name
- bank_branch_name
- bank_no
- claim_payment_date
- deadline
- fuel_cost_adjustment
- renewable_energy_cost
- total_amount
- total_amount_tax
- conventional_total_amount
- conventional_total_amount_tax
- difference
- notice
- tbl_user_id
- tbl_facility_id
- bank_type
- approval_flg
- bankacc_name_kana
- contract_customer_name
