---
:table_name: tbl_schedule
:table_type: :simple
:fields:
- id
- customer_id
- corporation_name
- title
- scheduled_type
- date
- day_used
- allday
- time_used
- start_time
- end_time
- holiday
- url
- editable
- memo
- deleted
- created
- modified
- tbl_account_id
- created_user_id
- modified_user_id
