---
:table_name: tbl_prediction_tmp
:table_type: :simple
:fields:
- customer_id
- dummy_customer_id
- pps_id
- district_id
- time
- power_loss
- type
- created
- created_user_id
- modified
- modified_user_id
