---
:table_name: tbl_bg_new
:table_type: :key_value
:fields:
- bg_name
- bg_leader_id
- business_kind
- tbl_district_id
- created
- created_user_id
- modified
- modified_user_id
- spot_position
- intraday_bidding_position
- district_name
- bg_leader_name
- code
