---
:table_name: tbl_profit_and_loss_calculation_fixed
:table_type: :simple
:fields:
- tbl_customer_id
- pps_id
- tbl_district_id
- time
- facility_name
- division_name
- supply_voltage_name
- voltage_name
- supply_name
- loss_rate
- actual_electrical_power
- planned_value
- loss_amount
- power_usage_part
- power_usage_total
- imbalance_surplus_amount
- Imbalance_shortage_amount
- power_factor_rate
- basic_rate_last_month
- meter_price
- fuel_cost_adjustment
- cost_adjustment
- special_discount
- total_sales_price
- kw_unit_price
- jbu_usage
- jepx_spot_usage
- jepx_one_hour_ago_usage
- etc1_usage
- etc2_usage
- etc3_usage
- jbu_basic
- jbu_quantity
- jbu_fuel_cost_adjustment
- jepx_spot_price
- jepx_one_hour_ago_charge
- etc1_charge
- etc2_charge
- etc3_charge
- imbalance_surplus_money
- imbalance_shortage_money
- commission_fee
- consigned_metering_fee
- kw_rate
- gross_profit
- profit_rate
- load_factor
- jbu_fuel_cost_included_rate
- jepx_spot_excluding_tax_rate
- jepx_fuel_cost_included_rate
- jepx_one_hour_ago_tax_excluded_rate
- jepx_one_hour_ago_rate
- power_source_rate1_rate
- power_source_rate2_rate
- power_source_rate3_rate
- imbalance_surplus_rate
- imbalance_shortage_rate
- consignment_rate
- alpha
- beta
- contract_item_group_id
- contract_item_group_name
- created
- created_user_id
- modified
- modified_user_id
