---
:table_name: tbl_claim_low
:table_type: :key_value
:fields:
- tbl_facility_id
- issue_date
- facility_number
- supplying_point_number
- company_zip
- company_address
- company_name
- company_department
- company_tel
- company_fax
- representative
- claim_ym
- total_amount
- total_amount_tax
- claim_payment_date
- supplying_point_address
- facility_name
- facility_person_in_charge
- period
- period_days
- claim_closing_date_current
- claim_closing_date_next
- contract_name
- max_demand_power
- usage_amount
- fuel_cost_adjustment_current
- fuel_cost_adjustment_next
- approval_flg
- created
- created_user_id
- modified
- tbl_user_id
- contract_customer_name
- claim_subject
- modified_user_id
- payment_method_id
- bankacc_name
- claim_destination_zip
- claim_destination_address
- bank_no
- bank_name
- bank_type
- bank_branch_name
- claim_destination_name
- bankacc_name_kana
- renewable_energy_cost
- claim_contract_name
- label_electricity_value
- electricity_value
- calc_month
