---
:table_name: tbl_pls_default
:table_type: :simple
:fields:
- id
- title
- regist_name
- regist_time
- pps_id
- district_id
- unit_price_jbu
- unit_price_other1
- unit_price_other2
- unit_price_other3
- unit_purchased_jepx500
- unit_purchased_jepx100
- unit_purchased_jbu
- unit_purchased_other1
- unit_purchased_other2
- unit_purchased_other3
- unit_purchased_inbalance_shortage
- unit_purchased_inbalance_surplus
- unit_max_jepx500
- unit_max_jepx100
- unit_max_jbu
- unit_max_other1
- unit_max_other2
- unit_max_other3
- unit_max_inbalance_shortage
- unit_max_inbalance_surplus
- unit_min_jepx500
- unit_min_jepx100
- unit_min_jbu
- unit_min_other1
- unit_min_other2
- unit_min_other3
- unit_min_inbalance_shortage
- unit_min_inbalance_surplus
- loss_rate
- beta_value
- before_hours_trading_rate
