---
:table_name: tbl_worksupport_step
:table_type: :key_value
:fields:
- tbl_worksupport_id
- tbl_workflow_step_id
- worksupport_step_date
- tbl_user_id
- worksupport_step_status
- worksupport_step_memo
- started
- ended
- created
- created_user_id
- modified
- modified_user_id
