---
:skip: true
:truncate: true
:model_class: Jepx::ImbalanceBeta
:sources:
- :fields:
    id: 
    year: 
    month: 
    district_id: 
    value: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: base_table_name
  :where: 0 = 0
