---
:skip: true
:truncate: true
:model_class: Jepx::SpotTrade
:sources:
- :fields:
    id: 
    date: 
    time_index_id: 
    sell_bit_amount: 
    buy_bit_amount: 
    execution_amount: 
    system_price: 
    avoidable_cost: 
    spot_avg_per_price: 
    alpha_max_times_spot_avg_per_price: 
    alpha_min_times_spot_avg_per_price: 
    alpha_preliminary_times_spot_avg_per_price: 
    alpha_fixed_times_spot_avg_per_price: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: base_table_name
  :where: 0 = 0
