target_model: DistrictLossRate
table_type: key_value
fields:
  tbl_district_id: district_id
  tbl_voltage_id: voltage_type_id
  voltage_loss_rate: rate
  application_start_ymd: application_start_date
  application_end_ymd: application_end_date
  created: created_at
  created_user_id:
  modified: updated_at
  modified_user_id:
