target_model: Facility
table_type: key_value
fields:
  id: id
  facility_name: name
  supplying_point_number: supply_point_number
  tbl_contract_customer_id: consumer_id
  facility_number: code
  payment_method_id:
  shipping_method_id:
  tbl_district_id: district_id
  claim_destination_flg:
  tbl_division_id:
  tbl_contract_id:
  tbl_voltage_id: voltage_type_id
  supply_voltage:
  contract_power_calc_method_id:
  consultation_power:
  contractcustomer_name:
  supply_method_id:
  district_name:
  base_power:
  division_name:
  tbl_observe_id:
  area_name:
  prediction_type_id:
  switching_flg:
  facility_characteristic:
  holiday_setting:
  vacation_memo:
  supply_start_date: supply_start_date
  supply_end_date: supply_end_date
  facility_tel: tel
  facility_fax: fax
  facility_email: email
  facility_url: url
  facility_zip: postral_code
  facility_pref: pref_no
  tbl_agency_id:
  agency_name:
  facility_city: city
  facility_address: address
  facility_person_in_charge: person_in_charge
  facility_person_in_charge_kana: person_in_charge_kana
  created: created_at
  company_name:
  created_user_id:
  modified: updated_at
  modified_user_id:
  pps_id:
  claim_closing_date:
  peak_shift_discount:
  spare_power_transmission:
  latitude:
  longitude:
  foreign_code_1:
  foreign_code_2:
  foreign_code_3:
  fuel_cost_calc_month_flg:
  auto_prediction:
  manual_priority_from:
  manual_priority_to:
