target_model: District
table_type: key_value
fields:
  district_code: code
  district_name: name
  high_voltage_loss_rate: loss_rate_high_voltage
  special_high_voltage_loss_rate: loss_rate_special_high_voltage
  low_voltage_loss_rate: loss_rate_low_voltage
  peaktime_from:
  peaktime_to:
  created: created_at
  created_user_id:
  modified: updated_at
  modified_user_id:
  summer_season_begin:
  summer_season_end:
  daytime_begin:
  daytime_end:
  holiday_judgement:
  jbu_peaktime:
  jbu_summer_daytime:
  jbu_other_daytime:
  jbu_night:
  beta:
  area_id:
  base_power_deduction_kbn:
