---
:skip: true
:truncate: true
:model_class: Dlt::File
:sources:
- :fields:
    id: 
    setting_id: 
    state: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: base_table_name
  :where: 0 = 0
