---
:skip: true
:truncate: true
:model_class: Dlt::InvalidSupplyPoint
:sources:
- :fields:
    id: 
    company_id: 
    district_id: 
    bg_member_id: 
    number: 
    name: 
    comment: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: 
  :where: 
