---
:truncate: true
:model_class: Dlt::Setting
:fields:
  id:
  company_id:
  district_id:
  state:
  created_at:
  updated_at:
:extra:
- :fields:
    company_id: 1
    district_id: 1
# :from: base_table_name
# :where: 0 = 0
