---
:truncate: true
:model_class: Dlt::Setting
:extra:
- :fields:
    company_id: 1
    district_id: 1
- :fields:
    company_id: 1
    district_id: 2
- :fields:
    company_id: 1
    district_id: 3
- :fields:
    company_id: 1
    district_id: 5
- :fields:
    company_id: 1
    district_id: 9
- :fields:
    company_id: 8
    district_id: 2
- :fields:
    company_id: 8
    district_id: 7
- :fields:
    company_id: 8
    district_id: 9
- :fields:
    company_id: 12
    district_id: 3
- :fields:
    company_id: 17
    district_id: 1
- :fields:
    company_id: 17
    district_id: 2
- :fields:
    company_id: 17
    district_id: 7
- :fields:
    company_id: 18
    district_id: 1
- :fields:
    company_id: 18
    district_id: 2
- :fields:
    company_id: 18
    district_id: 3
- :fields:
    company_id: 18
    district_id: 4
- :fields:
    company_id: 18
    district_id: 5
- :fields:
    company_id: 18
    district_id: 6
- :fields:
    company_id: 18
    district_id: 7
- :fields:
    company_id: 18
    district_id: 8
- :fields:
    company_id: 18
    district_id: 9
- :fields:
    company_id: 18
    district_id: 10
- :fields:
    company_id: 19
    district_id: 1
- :fields:
    company_id: 19
    district_id: 9
- :fields:
    company_id: 21
    district_id: 1
- :fields:
    company_id: 23
    district_id: 1
- :fields:
    company_id: 23
    district_id: 2
- :fields:
    company_id: 23
    district_id: 3
- :fields:
    company_id: 23
    district_id: 4
- :fields:
    company_id: 23
    district_id: 5
- :fields:
    company_id: 23
    district_id: 6
- :fields:
    company_id: 23
    district_id: 7
- :fields:
    company_id: 23
    district_id: 8
- :fields:
    company_id: 23
    district_id: 9
- :fields:
    company_id: 23
    district_id: 10
:sources: []
