---
:skip: true
:truncate: true
:model_class: Dlt::UsageFixedHeader
:sources:
- :fields:
    id: 
    facility_group_id: 
    information_type_code: 
    year: 
    month: 
    record_date: 
    sender_code: 
    receiver_code: 
    supply_point_number: 
    consumer_code: 
    consumer_name: 
    supply_point_name: 
    voltage_class_name: 
    journal_code: 
    can_provide: 
    usage_all: 
    usage: 
    power_factor: 
    max_power: 
    next_meter_reading_date: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: 
  :where: 
