---
:skip: true
:truncate: true
:model_class: BalancingGroup
:fields:
  id:
  code:
  name:
  district_id:
  leader_company_id:
  created_by:
  updated_by:
  created_at:
  updated_at:
:from: base_table_name
:where: 0 = 0
