---
:skip: true
:model_class: CompanyAccount
:truncate: true
:sources:
- :fields:
    id: ''
    company_id: 
    type: ''
    login_code: ''
    password: ''
    passphrase: 
    comment: ''
    created_by: ''
    updated_by: ''
    created_at: ''
    updated_at: ''
  :from: base_table_name
  :where: 0 = 0
