---
:fields:
  id: ''
  company_id: 'tbl_company.id'
  type: ''
  login_code: 'tbl_company.jepx_userid'
  password: 'tbl_company.jepx_password'
  comment: ''
  created_by: ''
  updated_by: ''
  created_at: ''
  updated_at: ''
:from: tbl_company
:where: "tbl_company.jepx_userid IS NOT NULL AND tbl_company.jepx_userid <> ''"
:model_class: CompanyAccountJepx
