---
:fields:
  id: tbl_company.id
  name: tbl_company.company_name
  code: ''
  name_kana: tbl_company.company_kana
  postal_code: tbl_company.zip
  pref_no: tbl_company.pref
  city: tbl_company.city
  address: tbl_company.address
  tel: tbl_company.tel
  fax: tbl_company.fax
  email: tbl_company.email
  created_by: tbl_company.created_user_id
  updated_by: tbl_company.modified_user_id
  created_at: tbl_company.created
  updated_at: tbl_company.modified
:from: tbl_company
# - logo_image_id
# - seal_image_id
# - allocate
# - taxtype
# - taxrate
# - fraction
# - fraction_tax
# - bankacc_name
# - approval_estimate
# - approval_received
# - approval_order
# - approval_claim
# - approval_sendmail_flg
# - tbl_user_id
# - us_user_name
# - tel1
# - tel2
# - tel3
# - account_key
# - fax1
# - fax2
# - fax3
# - ene_company_code
# - certificate_file_id
# - payment_site_id
# - payment_site_pass
# - certificate_key_file
# - alart_delivery_kbn
# - payment_site_flg
# - occto_userid
# - occto_password
# - occto_certificate_filename
# - jepx_userid
# - jepx_password
# - jepx_certificate_filename
# - claimlow_create_flg
