---
:model_class: Consumer
:truncate: true
:sources:
- :fields:
    id: tbl_contract_customer.id
    name: tbl_contract_customer.contractcustomer_name
    code: tbl_contract_customer.contractcustomer_number
    company_id: tbl_contract_customer.tbl_account_id
    tel: tbl_contract_customer.contractcustomer_tel
    fax: tbl_contract_customer.contractcustomer_fax
    email: tbl_contract_customer.contractcustomer_email
    url: tbl_contract_customer.contractcustomer_url
    postal_code: tbl_contract_customer.contractcustomer_zip
    pref_no: tbl_contract_customer.contractcustomer_pref
    city: tbl_contract_customer.contractcustomer_city
    address: tbl_contract_customer.contractcustomer_address
    person_in_charge: tbl_contract_customer.contractcustomer_person_in_charge
    person_in_charge_kana: tbl_contract_customer.contractcustomer_person_in_charge_kana
    password: tbl_contract_customer.contractcustomer_password
    created_by: tbl_contract_customer.created_user_id
    updated_by: tbl_contract_customer.modified_user_id
    created_at: tbl_contract_customer.created
    updated_at: tbl_contract_customer.modified
  :from: tbl_contract_customer
  :where: 0 = 0
