---
:truncate: true
:model_class: ContractMeterRate
:sources:
- :fields:
    id: id
    contract_id: tbl_contract_id
    contract_item_id: tbl_contract_item_id
    start_date: application_start_ymd
    end_date: application_end_ymd
    rate: CASE WHEN rate > 999999 THEN 999999 ELSE rate END
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_meter_rate
  :where: 0 = 0
