---
:truncate: true
:model_class: ContractItemGroup
:sources:
- :fields:
    id: id
    name: contract_item_group_name
    voltage_type_id: tbl_voltage_id
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_contract_item_group
  :where: 0 = 0
