---
:truncate: true
:model_class: ContractBasicCharge
:sources:
- :fields:
    id:
    contract_id: tbl_contract_id
    start_date: application_start_ymd
    amount: rate
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_basic_charge
  :where: 0 = 0
