---
:truncate: true
:model_class: District
:extra:
- :cond:
    id: 1
  :fields:
    dlt_host: https://pu00.www6.tepco.co.jp
    dlt_path: "/LNXWPWSS01OH/LNXWPWSS01I"
- :cond:
    id: 2
  :fields:
    dlt_host: https://www4.kepco.co.jp
    dlt_path: "/prx/000/http/kanden"
    is_partial_included: false
- :cond:
    id: 3
  :fields:
    dlt_host: https://epcdss-www.chuden.co.jp
    dlt_path: "/41294"
- :cond:
    id: 5
  :fields:
    dlt_host: https://takuso-web.takuso.tohoku-epco.co.jp
    dlt_path: "/G83PPS_Auto"
- :cond:
    id: 9
  :fields:
    dlt_host: https://nsc-www.network.kyuden.co.jp
    dlt_path: "/LNXWPWSS01I/App"
:sources:
- :fields:
    id: id
    name: district_name
    code: area_id
    wheeler_code: district_code
    loss_rate_special_high_voltage: special_high_voltage_loss_rate
    loss_rate_high_voltage: high_voltage_loss_rate
    loss_rate_low_voltage: low_voltage_loss_rate
    dlt_host: 
    dlt_path: 
    is_partial_included: 'TRUE'
    daytime_start_time_index_id: CASE daytime_begin WHEN '' THEN NULL ELSE ((SUBSTR(daytime_begin,
      1 ,2) * 2) + (SUBSTR(daytime_begin, 4 ,2) / 30) + 1) END
    daytime_end_time_index_id: CASE daytime_end WHEN '' THEN NULL ELSE ((SUBSTR(daytime_end,
      1 ,2) * 2) + (SUBSTR(daytime_end, 4 ,2) / 30) + 1) END
    peaktime_start_time_index_id: CASE peaktime_from WHEN '' THEN NULL ELSE ((SUBSTR(peaktime_from,
      1 ,2) * 2) + (SUBSTR(peaktime_from, 4 ,2) / 30) + 1) END
    peaktime_end_time_index_id: CASE peaktime_to WHEN '' THEN NULL ELSE ((SUBSTR(peaktime_to,
      1 ,2) * 2) + (SUBSTR(peaktime_to, 4 ,2) / 30) + 1) END
    summer_season_start_month: SUBSTR(summer_season_begin, 1 ,2)
    summer_season_end_month: SUBSTR(summer_season_end, 1 ,2)
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_district
  :where: tbl_district.id < 10
