---
:truncate: true
:model_class: District
:extra:
- :cond:
    id: 1
  :fields:
    dlt_host: https://pu00.www6.tepco.co.jp
    dlt_path: "/LNXWPWSS01OH/LNXWPWSS01I"
- :cond:
    id: 2
  :fields:
    dlt_host: https://www4.kepco.co.jp
    dlt_path: "/prx/000/http/kanden"
    is_partial_included: false
- :cond:
    id: 3
  :fields:
    dlt_host: https://epcdss-www.chuden.co.jp
    dlt_path: "/41294"
- :cond:
    id: 5
  :fields:
    dlt_host: https://takuso-web.takuso.tohoku-epco.co.jp
    dlt_path: "/G83PPS_Auto"
- :cond:
    id: 9
  :fields:
    dlt_host: https://nsc-www.network.kyuden.co.jp
    dlt_path: "/LNXWPWSS01I/App"
:sources:
- :fields:
    id: tbl_district.id
    name: tbl_district.district_name
    code: SUBSTRING(tbl_district.district_code, 5, 1)
    wheeler_code: tbl_district.district_code
    loss_rate_special_high_voltage: tbl_district.special_high_voltage_loss_rate
    loss_rate_high_voltage: tbl_district.high_voltage_loss_rate
    loss_rate_low_voltage: tbl_district.low_voltage_loss_rate
    dlt_host:
    dlt_path:
    is_partial_included: 'TRUE'
    created_by: tbl_district.created_user_id
    updated_by: tbl_district.modified_user_id
    created_at: tbl_district.created
    updated_at: tbl_district.modified
  :from: tbl_district
  :where: tbl_district.id < 10
