---
:skip: true
:fields:
  id: tbl_district.id
  name: tbl_district.district_name
  code: tbl_district.district_code
  loss_rate_special_high_voltage: tbl_district.special_high_voltage_loss_rate
  loss_rate_high_voltage: tbl_district.high_voltage_loss_rate
  loss_rate_low_voltage: tbl_district.low_voltage_loss_rate
  created_by: tbl_district.created_user_id
  updated_by: tbl_district.modified_user_id
  created_at: tbl_district.created
  updated_at: tbl_district.modified
:from: tbl_district
:where: tbl_district.id < 9
# :model_class: District
# :table_name: tbl_district
# :table_type: :key_value
# :fields:
# - district_code
# - district_name
# - high_voltage_loss_rate
# - special_high_voltage_loss_rate
# - peaktime_from
# - peaktime_to
# - created
# - created_user_id
# - modified
# - modified_user_id
# - low_voltage_loss_rate
# - summer_season_begin
# - summer_season_end
# - daytime_begin
# - daytime_end
# - holiday_judgement
# - jbu_peaktime
# - jbu_summer_daytime
# - jbu_other_daytime
# - jbu_night
# - beta
# - area_id
# - base_power_deduction_kbn
