---
:truncate: true
:model_class: ImbalanceKl
:sources:
- :fields:
    id: "'スキップ用ダミー'"
    district_id:
    start_date:
    k_value:
    l_value:
    created_by:
    updated_by:
    created_at:
    updated_at:
  :from: tbl_account
  :where: 1 = 0
