---
:skip: true
:truncate: true
:model_class: MatchingTradeSetting
:sources:
- :fields:
    id: "'スキップ用ダミー'"
    resource_id:
    year_pattern:
    month_pattern:
    day_pattern:
    day_of_week_pattern:
    time_index_1:
    time_index_2:
    time_index_3:
    time_index_4:
    time_index_5:
    time_index_6:
    time_index_7:
    time_index_8:
    time_index_9:
    time_index_10:
    time_index_11:
    time_index_12:
    time_index_13:
    time_index_14:
    time_index_15:
    time_index_16:
    time_index_17:
    time_index_18:
    time_index_19:
    time_index_20:
    time_index_21:
    time_index_22:
    time_index_23:
    time_index_24:
    time_index_25:
    time_index_26:
    time_index_27:
    time_index_28:
    time_index_29:
    time_index_30:
    time_index_31:
    time_index_32:
    time_index_33:
    time_index_34:
    time_index_35:
    time_index_36:
    time_index_37:
    time_index_38:
    time_index_39:
    time_index_40:
    time_index_41:
    time_index_42:
    time_index_43:
    time_index_44:
    time_index_45:
    time_index_46:
    time_index_47:
    time_index_48:
    created_by:
    updated_by:
    created_at:
    updated_at:
  :from: tbl_account
  :where: 1 = 0
:extra:
- :cond:
    id: 1
  :fields:
    resource_id: 38
    year_pattern: '*'
    month_pattern: '*'
    day_pattern: '*'
    day_of_week_pattern: '*'
    time_index_1: 1250
    time_index_2: 1250
    time_index_3: 1250
    time_index_4: 1250
    time_index_5: 1250
    time_index_6: 1250
    time_index_7: 1250
    time_index_8: 1250
    time_index_9: 1250
    time_index_10: 1250
    time_index_11: 1250
    time_index_12: 1250
    time_index_13: 1250
    time_index_14: 1250
    time_index_15: 1250
    time_index_16: 1250
    time_index_17: 1250
    time_index_18: 1250
    time_index_19: 1250
    time_index_20: 1250
    time_index_21: 1250
    time_index_22: 1250
    time_index_23: 1250
    time_index_24: 1250
    time_index_25: 1250
    time_index_26: 1250
    time_index_27: 1250
    time_index_28: 1250
    time_index_29: 1250
    time_index_30: 1250
    time_index_31: 1250
    time_index_32: 1250
    time_index_33: 1250
    time_index_34: 1250
    time_index_35: 1250
    time_index_36: 1250
    time_index_37: 1250
    time_index_38: 1250
    time_index_39: 1250
    time_index_40: 1250
    time_index_41: 1250
    time_index_42: 1250
    time_index_43: 1250
    time_index_44: 1250
    time_index_45: 1250
    time_index_46: 1250
    time_index_47: 1250
    time_index_48: 1250
- :cond:
    id: 2
  :fields:
    resource_id: 39
    year_pattern: '*'
    month_pattern: '*'
    day_pattern: '*'
    day_of_week_pattern: '*'
    time_index_1: 3000
    time_index_2: 3000
    time_index_3: 3000
    time_index_4: 3000
    time_index_5: 3000
    time_index_6: 3000
    time_index_7: 3000
    time_index_8: 3000
    time_index_9: 3000
    time_index_10: 3000
    time_index_11: 3000
    time_index_12: 3000
    time_index_13: 3000
    time_index_14: 3000
    time_index_15: 3000
    time_index_16: 3000
    time_index_17: 5000
    time_index_18: 5000
    time_index_19: 5000
    time_index_20: 5000
    time_index_21: 5000
    time_index_22: 5000
    time_index_23: 5000
    time_index_24: 5000
    time_index_25: 5000
    time_index_26: 5000
    time_index_27: 5000
    time_index_28: 5000
    time_index_29: 5000
    time_index_30: 5000
    time_index_31: 5000
    time_index_32: 5000
    time_index_33: 5000
    time_index_34: 5000
    time_index_35: 5000
    time_index_36: 5000
    time_index_37: 5000
    time_index_38: 5000
    time_index_39: 5000
    time_index_40: 5000
    time_index_41: 5000
    time_index_42: 5000
    time_index_43: 5000
    time_index_44: 5000
    time_index_45: 3000
    time_index_46: 3000
    time_index_47: 3000
    time_index_48: 3000
- :cond:
    id: 3
  :fields:
    resource_id: 40
    year_pattern: '*'
    month_pattern: '*'
    day_pattern: '*'
    day_of_week_pattern: '*'
    time_index_1: 0
    time_index_2: 0
    time_index_3: 0
    time_index_4: 0
    time_index_5: 0
    time_index_6: 0
    time_index_7: 0
    time_index_8: 0
    time_index_9: 0
    time_index_10: 0
    time_index_11: 0
    time_index_12: 0
    time_index_13: 0
    time_index_14: 0
    time_index_15: 0
    time_index_16: 0
    time_index_17: 500
    time_index_18: 500
    time_index_19: 500
    time_index_20: 500
    time_index_21: 500
    time_index_22: 500
    time_index_23: 500
    time_index_24: 500
    time_index_25: 500
    time_index_26: 500
    time_index_27: 500
    time_index_28: 500
    time_index_29: 500
    time_index_30: 500
    time_index_31: 500
    time_index_32: 500
    time_index_33: 500
    time_index_34: 500
    time_index_35: 500
    time_index_36: 500
    time_index_37: 2500
    time_index_38: 2500
    time_index_39: 2500
    time_index_40: 2500
    time_index_41: 2500
    time_index_42: 2500
    time_index_43: 2500
    time_index_44: 2500
    time_index_45: 2500
    time_index_46: 2500
    time_index_47: 2500
    time_index_48: 2500
