---
:skip: true
:truncate: true
:model_class: MatchingTradeSetting
:sources:
- :fields:
    id: "'スキップ用ダミー'"
    resource_id:
    year_pattern:
    month_pattern:
    day_pattern:
    day_of_week_pattern:
    time_index_1:
    time_index_2:
    time_index_3:
    time_index_4:
    time_index_5:
    time_index_6:
    time_index_7:
    time_index_8:
    time_index_9:
    time_index_10:
    time_index_11:
    time_index_12:
    time_index_13:
    time_index_14:
    time_index_15:
    time_index_16:
    time_index_17:
    time_index_18:
    time_index_19:
    time_index_20:
    time_index_21:
    time_index_22:
    time_index_23:
    time_index_24:
    time_index_25:
    time_index_26:
    time_index_27:
    time_index_28:
    time_index_29:
    time_index_30:
    time_index_31:
    time_index_32:
    time_index_33:
    time_index_34:
    time_index_35:
    time_index_36:
    time_index_37:
    time_index_38:
    time_index_39:
    time_index_40:
    time_index_41:
    time_index_42:
    time_index_43:
    time_index_44:
    time_index_45:
    time_index_46:
    time_index_47:
    time_index_48:
    created_by:
    updated_by:
    created_at:
    updated_at:
  :from: tbl_account
  :where: 1 = 0
