---
:truncate: true
:model_class: PowerGenerator
:sources:
- :fields:
    id: id
    power_generator_group_id: power_plant_bg_id
    code: code
    name: name
    contract_number: contract_no
    supply_max: supply_max
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_power_plant
  :where: 1 = 1
