---
:truncate: true
:model_class: PowerGeneratorGroup
:sources:
- :fields:
    id: "'スキップ用ダミー'"
    resource_id:
    contract_number:
    created_by:
    updated_by:
    created_at:
    updated_at:
  :from: tbl_account
  :where: 1 = 0
