---
:skip: true
:model_class: PowerUsagePreliminary
:truncate: true
:sources:
- :fields:
    id: ''
    facility_group_id: 
    date: ''
    time_index_id: ''
    value: ''
    created_by: ''
    updated_by: ''
    created_at: ''
    updated_at: ''
  :from: base_table_name
  :where: 0 = 0
