---
:model_class: Resource
:truncate: true
:sources:
:extra:
- :fields:
    balancing_group_id: 1
    type: ResourceSelf
    code: LA833
    name: エネオプBG東京需要
- :fields:
    balancing_group_id: 1
    type: ResourceJbu
    code: LA693
    name: 常時バックアップ(東京)
- :fields:
    balancing_group_id: 1
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
