---
:skip: true
:truncate: true
:model_class: ResourceJepxOneHour
:fields:
  id: 
  company_id: 
  code: 
  type: 
  name: 
  created_by: 
  updated_by: 
  created_at: 
  updated_at: 
:from: base_table_name
:where: 0 = 0
