---
:model_class: Resource
:truncate: true
:sources:
- :fields:
    id: "'スキップ用ダミー'"
    bg_member_id: 
    type: 
    code: 
    name: 
    contract_number: 
    max_value: 
    min_value: 
    unit: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: tbl_account
  :where: 1 = 0
:extra:
- :cond:
    id: 1
  :fields:
    bg_member_id: 1
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 2
  :fields:
    bg_member_id: 1
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 3
  :fields:
    bg_member_id: 1
    type: ResourceSelf
    code: LA833
    name: エネオプ東京需要BG
- :cond:
    id: 4
  :fields:
    bg_member_id: 1
    type: ResourceJbu
    code: LA693
    name: 常時バックアップ(東京)
- :cond:
    id: 5
  :fields:
    bg_member_id: 1
    type: ResourceMatching
    code: LC052
    name: エネオプ東北需要BG
- :cond:
    id: 6
  :fields:
    bg_member_id: 4
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 7
  :fields:
    bg_member_id: 4
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 8
  :fields:
    bg_member_id: 4
    type: ResourceSelf
    code: LA586
    name: エネオプ関西需要BG
- :cond:
    id: 9
  :fields:
    bg_member_id: 4
    type: ResourceJbu
    code: LA376
    name: 常時バックアップ(関西)
- :cond:
    id: 10
  :fields:
    bg_member_id: 4
    type: ResourceMatching
    code: LA456
    name: シナネン_06_L
- :cond:
    id: 11
  :fields:
    bg_member_id: 5
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 12
  :fields:
    bg_member_id: 5
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 13
  :fields:
    bg_member_id: 5
    type: ResourceSelf
    code: LA514
    name: エネオプ中部需要BG
- :cond:
    id: 14
  :fields:
    bg_member_id: 5
    type: ResourceJbu
    code: LA304
    name: 常時バックアップ(中部)
- :cond:
    id: 15
  :fields:
    bg_member_id: 7
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 16
  :fields:
    bg_member_id: 7
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 17
  :fields:
    bg_member_id: 7
    type: ResourceSelf
    code: LC052
    name: エネオプ東北需要BG
- :cond:
    id: 18
  :fields:
    bg_member_id: 7
    type: ResourceMatching
    code: LA833
    name: エネオプ東京需要BG
- :cond:
    id: 19
  :fields:
    bg_member_id: 9
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 20
  :fields:
    bg_member_id: 9
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 21
  :fields:
    bg_member_id: 9
    type: ResourceSelf
    code: LA289
    name: アメニティ九州需要BG
- :cond:
    id: 22
  :fields:
    bg_member_id: 9
    type: ResourceJbu
    code: G0449
    name: 九州電力(小売・発電)自社発電ＢＧ
- :cond:
    id: 23
  :fields:
    bg_member_id: 9
    type: ResourceFit
    code: G0449
    name: 九州電力(小売・発電)自社発電ＢＧ
- :cond:
    id: 24
  :fields:
    bg_member_id: 9
    type: ResourceMatching
    code: LB439
    name: エネオプ九州需要BG
- :cond:
    id: 25
  :fields:
    bg_member_id: 21
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 26
  :fields:
    bg_member_id: 21
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 27
  :fields:
    bg_member_id: 21
    type: ResourceSelf
    code: LD777
    name: エネオプ中国需要BG
- :cond:
    id: 28
  :fields:
    bg_member_id: 21
    type: ResourceMatching
    code: LA586
    name: エネオプ関西需要BG
- :cond:
    id: 29
  :fields:
    bg_member_id: 24
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 30
  :fields:
    bg_member_id: 24
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 31
  :fields:
    bg_member_id: 24
    type: ResourceSelf
    code: LB439
    name: エネオプ九州需要BG
- :cond:
    id: 32
  :fields:
    bg_member_id: 24
    type: ResourceMatching
    code: LA289
    name: アメニティ九州需要BG
- :cond:
    id: 33
  :fields:
    bg_member_id: 27
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 34
  :fields:
    bg_member_id: 27
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 35
  :fields:
    bg_member_id: 27
    type: ResourceSelf
    code: LG533
    name: 京葉瓦斯（需要BG）
- :cond:
    id: 36
  :fields:
    bg_member_id: 27
    type: ResourceJbu
    code: LA693
    name: 常時バックアップ(東京)
- :cond:
    id: 37
  :fields:
    bg_member_id: 27
    type: ResourceFit
    code: G0633
    name: 京葉瓦斯株式会社
- :cond:
    id: 38
  :fields:
    bg_member_id: 27
    type: ResourceMatching
    code: G0013
    name: 東京ガス社相対電源
    #supply_value: 1250
- :cond:
    id: 39
  :fields:
    bg_member_id: 27
    type: ResourceMatching
    code: G0143
    name: ダイヤモンドパワー社相対電源
    #supply_value: if time_index_id >= 17 and time_index_id <= 44 then 5000 else 3000 end
- :cond:
    id: 40
  :fields:
    bg_member_id: 27
    type: ResourceMatching
    code: LB703
    name: FNJ東京
    #supply_value: case when (time_index_id >= 17 and time_index_id <= 36); 500 when time_index_id >= 37; 2500 else 0 end
- :cond:
    id: 41
  :fields:
    bg_member_id: 33
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 42
  :fields:
    bg_member_id: 33
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 43
  :fields:
    bg_member_id: 33
    type: ResourceSelf
    code: LG838
    name: エネオプ四国需要BG
- :cond:
    id: 44
  :fields:
    bg_member_id: 43
    type: ResourceJepxSpot
    code: JSPT3
    name: スポット
- :cond:
    id: 45
  :fields:
    bg_member_id: 43
    type: ResourceJepxOneHour
    code: J1HR3
    name: 1時間前
- :cond:
    id: 46
  :fields:
    bg_member_id: 43
    type: ResourceSelf
    code: LJ381
    name: エネオプ北海道需要BG
