---
:skip: true
:truncate: true
:model_class: ResourceFit
:sources:
- :fields:
    id: 
    bg_member_id: 
    type: 
    code: 
    name: 
    supply_value: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: base_table_name
  :where: 0 = 0
