---
:model_class: SupplyPoint
:truncate: true
:sources:
- :fields:
    id:
    number: tbl_facility.supplying_point_number
    supply_start_date: tbl_facility.supply_start_date
    supply_end_date: tbl_facility.supply_end_date
    supply_method_type: CASE tbl_facility.supply_method_id WHEN '1' THEN 'supply_method_type_all'
      WHEN '2' THEN 'supply_method_type_partial' END
    base_power: CASE tbl_facility.supply_method_id WHEN '1' THEN NULL ELSE tbl_facility.base_power
      END
    facility_group_id: CASE WHEN tbl_facility.tbl_voltage_id = '1' || tbl_facility.tbl_voltage_id
      = '2' THEN tbl_facility.id ELSE tbl_low_power_group_supplying_point_number.tbl_facility_high_power_id
      END
    facility_id: tbl_facility.id
    created_by: tbl_facility.created_user_id
    updated_by: tbl_facility.modified_user_id
    created_at: tbl_facility.created
    updated_at: tbl_facility.modified
  :from: tbl_facility
  :where: tbl_voltage_id < 99 AND tbl_voltage_id AND tbl_facility.pps_id NOT IN(2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15)
  :joins:
  - :table: tbl_low_power_group_supplying_point_number
    :type: outer
    :on: tbl_facility.id = tbl_low_power_group_supplying_point_number.tbl_facility_low_power_id
- :fields:
    id:
    number: supplying_point_number
    supply_start_date: supply_start_date
    supply_end_date: supply_end_date
    supply_method_type: "'supply_method_type_all'"
    base_power:
    facility_group_id: tbl_facility_high_power_id
    facility_id:
    created_by: created_user_id
    updated_by: modified_user_id
    created_at: created
    updated_at: modified
  :from: tbl_low_power_group_supplying_point_number
  :where: tbl_facility_low_power_id IS NULL
