---
:skip: true
:model_class: TimeIndex
:truncate: true
:sources:
- :fields:
    id: ''
    time: ''
    created_by: ''
    updated_by: ''
    created_at: ''
    updated_at: ''
  :from: base_table_name
  :where: 0 = 0
-
  -
    :fields:
      id: 1
      time: '00:00'
  -
    :fields:
      id: 2
      time: '00:30'
  -
    :fields:
      id: 3
      time: '01:00'
  -
    :fields:
      id: 4
      time: '01:30'
  -
    :fields:
      id: 5
      time: '02:00'
  -
    :fields:
      id: 6
      time: '02:30'
  -
    :fields:
      id: 7
      time: '03:00'
  -
    :fields:
      id: 8
      time: '03:30'
  -
    :fields:
      id: 9
      time: '04:00'
  -
    :fields:
      id: 10
      time: '04:30'
  -
    :fields:
      id: 11
      time: '05:00'
  -
    :fields:
      id: 12
      time: '05:30'
  -
    :fields:
      id: 13
      time: '06:00'
  -
    :fields:
      id: 14
      time: '06:30'
  -
    :fields:
      id: 15
      time: '07:00'
  -
    :fields:
      id: 16
      time: '07:30'
  -
    :fields:
      id: 17
      time: '08:00'
  -
    :fields:
      id: 18
      time: '08:30'
  -
    :fields:
      id: 19
      time: '09:00'
  -
    :fields:
      id: 20
      time: '09:30'
  -
    :fields:
      id: 21
      time: '10:00'
  -
    :fields:
      id: 22
      time: '10:30'
  -
    :fields:
      id: 23
      time: '11:00'
  -
    :fields:
      id: 24
      time: '11:30'
  -
    :fields:
      id: 25
      time: '12:00'
  -
    :fields:
      id: 26
      time: '12:30'
  -
    :fields:
      id: 27
      time: '13:00'
  -
    :fields:
      id: 28
      time: '13:30'
  -
    :fields:
      id: 29
      time: '14:00'
  -
    :fields:
      id: 30
      time: '14:30'
  -
    :fields:
      id: 31
      time: '15:00'
  -
    :fields:
      id: 32
      time: '15:30'
  -
    :fields:
      id: 33
      time: '16:00'
  -
    :fields:
      id: 34
      time: '16:30'
  -
    :fields:
      id: 35
      time: '17:00'
  -
    :fields:
      id: 36
      time: '17:30'
  -
    :fields:
      id: 37
      time: '18:00'
  -
    :fields:
      id: 38
      time: '18:30'
  -
    :fields:
      id: 39
      time: '19:00'
  -
    :fields:
      id: 40
      time: '19:30'
  -
    :fields:
      id: 41
      time: '20:00'
  -
    :fields:
      id: 42
      time: '20:30'
  -
    :fields:
      id: 43
      time: '21:00'
  -
    :fields:
      id: 44
      time: '21:30'
  -
    :fields:
      id: 45
      time: '22:00'
  -
    :fields:
      id: 46
      time: '22:30'
  -
    :fields:
      id: 47
      time: '23:00'
  -
    :fields:
      id: 48
      time: '23:30'
