---
:skip: true
:fields:
  id: ''
  name: ''
  password: ''
  accesable_type: ''
  accesable_id: ''
  created_by: ''
  updated_by: ''
  created_at: ''
  updated_at: ''
:from: base_table_name
:where: 0 = 0
:model_class: User
:truncate: true
