---
:skip: true
:truncate: true
:model_class: BalancingGroup::HABTM_Companies
:sources:
- :fields:
    id: 
    balancing_group_id: 
    company_id: 
    created_by: 
    updated_by: 
    created_at: 
    updated_at: 
  :from: base_table_name
  :where: 0 = 0
