---
:skip: true
:truncate: true
:model_class: Company::HABTM_BalancingGroups
:fields:
  id:
  balancing_group_id:
  company_id:
  created_by:
  updated_by:
  created_at:
  updated_at:
:from: base_table_name
:where: 0 = 0
